config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resource :histories

  get 'histories' => 'histories#index'

  root 'posts#index'

  get 'api/histories/last-week/bubble' => 'histories#last_week_bubble_api'

  get 'api/histories/all' => 'histories#all_api'

  get 'histories' => 'histories#index', as: :personal_history

end

app/models/history.rb
class History < ActiveRecord::Base
	default_scope -> { order('created_at DESC')}
	scope :created_on, lambda {|date| {:conditions => ['created_at >= ? AND created_at <= ?', date.beginning_of_day, date.end_of_day]}}

	validates_uniqueness_of :tag

	def self.today
		where("created_at BETWEEN '#{DateTime.now.beginning_of_day}' AND '#{DateTime.now.end_of_day}'")
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	include Elasticsearch::Model
  	include Elasticsearch::Model::Callbacks
	
	default_scope -> { order('created_at DESC')}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_history

  private

  def set_history
  	@history = History.new
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
	before_action :set_history, only: [:edit, :update, :destroy]

	def index
		@histories = History.all
	end

	def show
    @history = History.new
    @histories = History.all
    @today = History.today
	end

	def create
		tags = params["history"]["tag"].split(',')
		tags.each do |t|
    	@history = History.new({
        tagday: Time.now.to_date.to_s,
        tag: Time.now.to_date.to_s + '|' + t,
        tagline: t
      })
    	@history.save
    	# saves unique histories that are unique by the Day
    end
		respond_to do |format|
      format.html { render nothing: true }
      format.json { render nothing: true }
    end
  end

  def all_api
    all_tags = History.all.map { |h| {
      tagday: h["tagday"],
      tagline: h["tagline"] }
    }
    respond_to do |format|
      format.json { render json: all_tags }
    end
  end

  def last_week_bubble_api
    uniq_taglines = History.all.map { |h| h["tagline"] }.uniq

    all_tags = History.all.map { |h| {
      tagday: h["tagday"],
      tagline: h["tagline"] }
    }


    stage1 = uniq_taglines.map do |tagline|
      { 
        tagline: tagline,
        tagdays: all_tags.map { |h| h[:tagday] if h[:tagline] == tagline }
          .compact
      }
    end

    stage2 = stage1.map do |tag|
      {
        tagday: tag[:tagdays][0],
        tagline: tag[:tagline],
        size: tag[:tagdays].length
      }
    end
    # TODO: index these substages.
    stage3_0 = stage2.chunk { |day| 0.day.ago.to_date.to_s if 
      day[:tagday] == 0.day.ago.to_date.to_s }
      .map { |date, ary| 
        {
          name: date,
          children: ary.map { |h| { name: h[:tagline], size: h[:size] } }
        }
      }

    stage3_1 = stage2.chunk { |day| 1.day.ago.to_date.to_s if 
      day[:tagday] == 1.day.ago.to_date.to_s }
      .map { |date, ary| 
        {
          name: date,
          children: ary.map { |h| { name: h[:tagline], size: h[:size] } }
        }
      }

    stage3_2 = stage2.chunk { |day| 2.day.ago.to_date.to_s if 
      day[:tagday] == 2.day.ago.to_date.to_s }
      .map { |date, ary| 
        {
          name: date,
          children: ary.map { |h| { name: h[:tagline], size: h[:size] } }
        }
      }

    stage3_3 = stage2.chunk { |day| 3.day.ago.to_date.to_s if 
      day[:tagday] == 3.day.ago.to_date.to_s }
      .map { |date, ary| 
        {
          name: date,
          children: ary.map { |h| { name: h[:tagline], size: h[:size] } }
        }
      }

    stage3_4 = stage2.chunk { |day| 4.day.ago.to_date.to_s if 
      day[:tagday] == 4.day.ago.to_date.to_s }
      .map { |date, ary| 
        {
          name: date,
          children: ary.map { |h| { name: h[:tagline], size: h[:size] } }
        }
      }

    stage3_5 = stage2.chunk { |day| 5.day.ago.to_date.to_s if 
      day[:tagday] == 5.day.ago.to_date.to_s }
      .map { |date, ary| 
        {
          name: date,
          children: ary.map { |h| { name: h[:tagline], size: h[:size] } }
        }
      }

    stage3_6 = stage2.chunk { |day| 6.day.ago.to_date.to_s if 
      day[:tagday] == 6.day.ago.to_date.to_s }
      .map { |date, ary| 
        {
          name: date,
          children: ary.map { |h| { name: h[:tagline], size: h[:size] } }
        }
      }

    stage3 = stage3_0 + stage3_1 + stage3_2 + stage3_3 + stage3_4 + stage3_5 + stage3_6
           
    stage4 = {
      name: "flare",
      children: stage3
    }

  	tags = History.all.map { |h| h["tag"] }
  	respond_to do |format|
  		format.json { render json: stage4 }
  	end
  end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tags
      params.require(:history).find(:tag)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @history = History.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @history = History.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_url, notice: 'Post was successfully created.' }
        format.json { render root_url, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body_html, :mood)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/index.html.erb
<nav class="admin">
	<div class="left">
		<i class="publish-icon">publish</i>
	</div>
	<div class="middle">
		This is the blog title
	</div>
	<div class="settings right">
		<i class="gear-icon">gear</i>
		<ul>
			<li>HTML / CSS</li>
			<li>Account</li>
			<li>Logout</li>
		</ul>
	</div>
</nav>

<div class="sidebar">
	<a href="#">New Post</a>
	<ul class="month-years">
		<li>
			Month Year
		</li>
		<li>
			Month Year
		</li>
		<li>
			Month Year
		</li>
		<li>
			Month Year
		</li>
		<li>
			Month Year
		</li>
	</ul>

</div>

<div class="main">
	<header>
		<h1>Title Goes Here</h1>
	</header>

	<section class="posts">
		<% for i in 1..5 %>
		<article class="post">
			<header>
				<h2>This is a post header</h2>
			</header>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<p>
				Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
			</p>
			<p>
				Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>

		</article>
		<% end %>

	</section>

</div>

app/views/histories/show.html.erb
<!-- Graph Javascript -->
<script>

</script>


<!-- Place it to the left of the sidebar -->
<div class="main">
	<% if @histories.length > 0 %>

	<section class="graph">
		<header>
			<h2>Histories Bubble Graph</h2>
			<p>
				What do you tend to do the most nowadays? This bubble graph measures your habits by darkening the circles which represent things you have most recently done, and enlargening the circles of things which you tend to (log and) do a lot.
			</p>
		</header>
		<div id="histories-bubble-graph">
		</div>
	</section>

	<section class="new-history">
		<%= form_for(@history, remote: true) do |f| %>
      <div>

        <%= f.text_field :tag, class: 'tags-input', value: 'logged a new entry,am alive' %>
        <small class="centered">
          Per Day. Use common phrases to track common achievements, activities, failures, and milestones.
        </small>
      </div>
      <%= f.submit 'Log New History',
	      'class' => 'btn btn-primary',
	      'id' => 'log-history-page-btn'
	      %>
    <% end %>	
	</section>

	<section class="history">
		<header>
			<h2>All Logged History</h2>
			<p>
				Including a list of all logged histories, ordered by most recently logged.
			</p>
		</header>
		<div id="all-history">
			<ol>
				<% for hist in @histories %>
				<li><%= hist.tagline %> 
					<small class="subtle"><%= hist.created_at.to_date %></small>
				</li>
				<% end %>
			</ol>
		</div>
	</section>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>habits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="admin">
  <div class="left">
    <%= link_to 'Create Note', new_post_path %>
    <a href="#" data-toggle="modal" data-target="#myModal">
      Log History
    </a>
    <%= link_to 'View History', personal_history_path %>
  </div>
  <div class="middle">
    <a href="/">Your Personal Notebook</a>
  </div>
  <div class="settings right">
    <i class="gear-icon">gear</i>
    <ul>
      <li>HTML / CSS</li>
      <li>Account</li>
      <li>Logout</li>
    </ul>
  </div>
</nav>


<div class="sidebar">
  <%= link_to 'New Post', new_post_path %>
  <br>
  <!-- Button trigger modal -->
  <a href="#" data-toggle="modal" data-target="#myModal">
    Log History
  </a>

  <ul class="month-years">
    <li>
      Month Year
    </li>
    <li>
      Month Year
    </li>
    <li>
      Month Year
    </li>
    <li>
      Month Year
    </li>
    <li>
      Month Year
    </li>
  </ul>

</div>


<div class="content">

  <%= yield %>


  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">
            Log a History <span class="subtle">or two</span>
          </h4>
        </div>
        <%= form_for(@history, remote: true) do |f| %>
        <div class="modal-body">

          <%= f.text_field :tag, class: 'tags-input', value: 'logged a new entry,am alive' %>
          <small class="centered">
            Per Day. Use common phrases to track common achievements, activities, failures, and milestones.
          </small>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          
          <%= f.submit 'Log History',
              'class' => 'btn btn-primary',
              'id' => 'log-history-btn'
              %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, required: true, placeholder: "title" %>
  </div>
  <div class="field">
    <%= f.text_area :body_html %>
  </div>

  <div  class="emoticons-bar centered"
        id="choose-note-emoticons-bar">
    <p>
      Choose the mood that best represents your overall post.
    </p>
    <div class="emoticon emoticon-1" data-mood="1" title="extreme sadness"></div>
    <div class="emoticon emoticon-2" data-mood="2"></div>
    <div class="emoticon emoticon-3" data-mood="3"></div>
    <div class="emoticon emoticon-4" data-mood="4"></div>
    <div class="emoticon emoticon-5" data-mood="5" title="meh, neutral"></div>
    <div class="emoticon emoticon-6" data-mood="6"></div>
    <div class="emoticon emoticon-7" data-mood="7"></div>
    <div class="emoticon emoticon-8" data-mood="8"></div>
    <div class="emoticon emoticon-9" data-mood="9" title="extreme happiness"></div>
  </div>

  <%= f.hidden_field :mood %>

  <div class="actions">
    <%= f.submit 'Create Note', id: 'create-note-btn' %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<div class="form">
<h1>Editing</h1>

<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<div class="main">
  <header>
    <h1>Title Goes Here</h1>
  </header>

  <section class="posts">
    <% if false %>
    <article class="post">
      <header>
        <h2>This is a post header</h2>
        <small>
          Edit
        </small>
        <small>
          Delete 
        </small>
      </header>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <p>
        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
      </p>
      <p>
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>

    </article>
    <% end %>

    <% @posts.each do |post| %>
      <article class="post">
        <header>
          <h2><%= link_to post.title, post %></h2>
          <%= post.updated_at.to_date %>
          <small>
            <%= link_to 'Edit', edit_post_path(post) %>
          </small>
          <small>
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          </small>
        </header>
        <%= raw post.body_html %>
        <p class="read-more">
          +
        </p>
      </article>
        
    <% end %>

  </section>

</div>

app/views/posts/new.html.erb
<div class="form">
<h1>New</h1>

<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div class="form">
<article class="post">
<header>
	<h2><%= @post.title %></h2>
</header>

<%= raw @post.body_html %>

</article>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>